// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'ui_text.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

TranslationLanguage _$TranslationLanguageFromJson(Map<String, dynamic> json) =>
    TranslationLanguage(
      json['langInitial'] as String,
      Uri.parse(json['langFilePath'] as String),
      json['selected'] as bool,
    );

Map<String, dynamic> _$TranslationLanguageToJson(
        TranslationLanguage instance) =>
    <String, dynamic>{
      'langInitial': instance.langInitial,
      'langFilePath': instance.langFilePath.toString(),
      'selected': instance.selected,
    };

TranslationText _$TranslationTextFromJson(Map<String, dynamic> json) =>
    TranslationText(
      json['pathsReselectBtnText'] as String,
      json['foldersBtnText'] as String,
      json['modsFolderBtnText'] as String,
      json['backupFolderBtnText'] as String,
      json['deletedItemsBtnText'] as String,
      json['checksumBtnText'] as String,
      json['checksumMissingBtnText'] as String,
      json['modSetsBtnText'] as String,
      json['modListBtnText'] as String,
      json['previewBtnText'] as String,
      json['lightModeBtnText'] as String,
      json['darkModeBtnText'] as String,
      json['pathsReselectTooltipText'] as String,
      json['foldersTooltipText'] as String,
      json['modsFolderTooltipText'] as String,
      json['checksumToolTipText'] as String,
      json['modSetsTooltipText'] as String,
      json['previewTooltipText'] as String,
      json['lightModeTooltipText'] as String,
      json['darkModeTooltipText'] as String,
      json['languageTooltipText'] as String,
      json['itemsHeaderText'] as String,
      json['availableModsHeaderText'] as String,
      json['previewHeaderText'] as String,
      json['appliedModsHeadersText'] as String,
      json['setsHeaderText'] as String,
      json['modsInSetHeaderText'] as String,
      json['refreshBtnTootipText'] as String,
      json['newCatBtnTooltipText'] as String,
      json['newItemBtnTooltipText'] as String,
      json['inExplorerBtnTootipText'] as String,
      json['searchLabelText'] as String,
      json['newCatNameLabelText'] as String,
      json['addCatBtnText'] as String,
      json['singleAddBtnText'] as String,
      json['multiAddBtnText'] as String,
      json['singleDropBoxLabelText'] as String,
      json['multiDropBoxLabelText'] as String,
      json['iconDropBoxLabelText'] as String,
      json['addSelectCatLabelText'] as String,
      json['addItemNamLabelText'] as String,
      json['addModNameLabelText'] as String,
      json['addModTootipText'] as String,
      json['addModToTooltipText'] as String,
      json['favLabelText'] as String,
      json['accessoriesLabelText'] as String,
      json['basewearsLabelText'] as String,
      json['bodypaintsLabelText'] as String,
      json['emotesLabelText'] as String,
      json['innerLabelText'] as String,
      json['miscLabelText'] as String,
      json['motionsLabelText'] as String,
      json['outerLabelText'] as String,
      json['setwearsLabelText'] as String,
      json['unapplyThisModTooltipText'] as String,
      json['applyThisModTooltipText'] as String,
      json['modNameLabelText'] as String,
      json['modsSetSaveTooltipText'] as String,
      json['modsSetClickTooltipText'] as String,
      json['applyModUnderTooltipText'] as String,
      json['toTheGameTooltipText'] as String,
      json['unapplyModUnderTooltipText'] as String,
      json['fromTheGameTooltipText'] as String,
      json['newSetNameLabelText'] as String,
      json['addNewSetTootipText'] as String,
      json['addSetBtnText'] as String,
      json['holdToDeleteBtnTooltipText'] as String,
      json['holdToRemoveBtnTooltipText'] as String,
      json['holdToReapplyBtnTooltipText'] as String,
      json['holdToRemoveAllBtnTooltipText'] as String,
      json['itemsLabelText'] as String,
      json['itemLabelText'] as String,
      json['fileAppliedColonLabelText'] as String,
      json['fileAppliedLabelText'] as String,
      json['closeBtnText'] as String,
      json['openBtnTooltipText'] as String,
      json['addBtnText'] as String,
      json['addBtnTooltipText'] as String,
      json['removeBtnTooltipText'] as String,
      json['deleteBtnTooltipText'] as String,
      json['refreshingLabelText'] as String,
      json['modscolonLableText'] as String,
      json['appliedcolonLabelText'] as String,
      json['toFavTooltipText'] as String,
      json['fromFavTooltipText'] as String,
      json['doneBtnText'] as String,
      json['filesLabelText'] as String,
      json['fileLabelText'] as String,
      json['curFilesInSetAppliedTooltipText'] as String,
      json['deleteCatPopupText'] as String,
      json['deleteCatPopupMsgText'] as String,
      json['cannotDeleteCatPopupText'] as String,
      json['cannotDeleteCatPopupUnapplyText'] as String,
      json['deleteItemPopupText'] as String,
      json['deleteItemPopupMsgText'] as String,
      json['deleteModPopupText'] as String,
      json['deleteModPopupMsgText'] as String,
      json['unappyFilesFirstMsgText'] as String,
      json['removeFromFavFirstMsgText'] as String,
      json['noSearchResultFoundText'] as String,
      json['fromText'] as String,
      json['loadingUIText'] as String,
      json['checksumSelectPopupText'] as String,
      json['newUpdateAvailText'] as String,
      json['newAppVerText'] as String,
      json['curAppVerText'] as String,
      json['patchNoteLabelText'] as String,
      json['updateBtnText'] as String,
      json['dismissBtnText'] as String,
      json['waitingUserActionText'] as String,
      json['pso2binReselectPopupText'] as String,
      json['modmanReselectPopupText'] as String,
      json['curPathText'] as String,
      json['chooseNewPathText'] as String,
      json['newCatNameEmptyErrorText'] as String,
      json['newCatNameDupErrorText'] as String,
      json['newItemNameEmpty'] as String,
      json['newItemNameDuplicate'] as String,
      json['multiItemsLeftOver'] as String,
      json['originalFileOf'] as String,
      json['isNotFound'] as String,
      json['replaced'] as String,
      json['backupFileOf'] as String,
      json['setRemovalErrorText'] as String,
      json['pso2binNotFoundPopupText'] as String,
      json['modmanFolderNotFoundLabelText'] as String,
      json['modmanFolderNotFoundText'] as String,
      json['addModsBtnLabel'] as String,
      json['addModsTooltip'] as String,
      json['checksumDownloadingBtnLabel'] as String,
      json['itemRefUpdateAvailableText'] as String,
      json['downloadingText'] as String,
      json['filesOfText'] as String,
      json['downloadUpdateBtnLabel'] as String,
      json['sortCategoryTooltipText'] as String,
      json['sortCateByNameText'] as String,
      json['sortCateByNumItemsText'] as String,
      json['preparingLabelText'] as String,
      json['dragNdropBoxLabelText'] as String,
      json['removeBtnLabel'] as String,
      json['clearAllBtnLabel'] as String,
      json['progressBtnLabel'] as String,
      json['waitingForDataLabelText'] as String,
      json['errorLoadingRestartApp'] as String,
      json['editTooltipText'] as String,
      json['renameSpaceLabelText'] as String,
      json['spaceBeforeAddingLabelText'] as String,
      json['errorModsInToBeAddedListLabelText'] as String,
      json['returnBtnLabel'] as String,
      json['addAllBtnLabelText'] as String,
      json['errorFilesNotSupportedText'] as String,
      json['checksumHoldBtnTooltip'] as String,
      json['modsLabelText'] as String,
      json['modLabelText'] as String,
      json['modAddedSuccessfullyText'] as String,
      json['preparingItemsText'] as String,
      json['mayTakeSomeTimeText'] as String,
      json['removeItemFromAdding'] as String,
      json['removeModFromAdding'] as String,
      json['addItemBackToAdding'] as String,
      json['addModBackToAdding'] as String,
      json['newUserNoticeText'] as String,
      json['clickContinueIfStuckBtnLabel'] as String,
      json['skipVersionUpdateBtnLabel'] as String,
      json['singleFileAppliedLabelText'] as String,
      json['titleNewUpdateToolTip'] as String,
      json['nameCannotBeEmptyErrorText'] as String,
      json['nameAlreadyExistsErrorText'] as String,
      json['checksumOutdatedErrorText'] as String,
      json['downloadChecksumFirstTooltipText'] as String,
    );

Map<String, dynamic> _$TranslationTextToJson(TranslationText instance) =>
    <String, dynamic>{
      'pathsReselectBtnText': instance.pathsReselectBtnText,
      'foldersBtnText': instance.foldersBtnText,
      'modsFolderBtnText': instance.modsFolderBtnText,
      'backupFolderBtnText': instance.backupFolderBtnText,
      'deletedItemsBtnText': instance.deletedItemsBtnText,
      'checksumBtnText': instance.checksumBtnText,
      'checksumMissingBtnText': instance.checksumMissingBtnText,
      'modSetsBtnText': instance.modSetsBtnText,
      'modListBtnText': instance.modListBtnText,
      'previewBtnText': instance.previewBtnText,
      'lightModeBtnText': instance.lightModeBtnText,
      'darkModeBtnText': instance.darkModeBtnText,
      'pathsReselectTooltipText': instance.pathsReselectTooltipText,
      'foldersTooltipText': instance.foldersTooltipText,
      'modsFolderTooltipText': instance.modsFolderTooltipText,
      'checksumToolTipText': instance.checksumToolTipText,
      'modSetsTooltipText': instance.modSetsTooltipText,
      'previewTooltipText': instance.previewTooltipText,
      'lightModeTooltipText': instance.lightModeTooltipText,
      'darkModeTooltipText': instance.darkModeTooltipText,
      'languageTooltipText': instance.languageTooltipText,
      'itemsHeaderText': instance.itemsHeaderText,
      'availableModsHeaderText': instance.availableModsHeaderText,
      'previewHeaderText': instance.previewHeaderText,
      'appliedModsHeadersText': instance.appliedModsHeadersText,
      'setsHeaderText': instance.setsHeaderText,
      'modsInSetHeaderText': instance.modsInSetHeaderText,
      'refreshBtnTootipText': instance.refreshBtnTootipText,
      'newCatBtnTooltipText': instance.newCatBtnTooltipText,
      'newItemBtnTooltipText': instance.newItemBtnTooltipText,
      'inExplorerBtnTootipText': instance.inExplorerBtnTootipText,
      'searchLabelText': instance.searchLabelText,
      'newCatNameLabelText': instance.newCatNameLabelText,
      'addCatBtnText': instance.addCatBtnText,
      'singleAddBtnText': instance.singleAddBtnText,
      'multiAddBtnText': instance.multiAddBtnText,
      'singleDropBoxLabelText': instance.singleDropBoxLabelText,
      'multiDropBoxLabelText': instance.multiDropBoxLabelText,
      'iconDropBoxLabelText': instance.iconDropBoxLabelText,
      'addSelectCatLabelText': instance.addSelectCatLabelText,
      'addItemNamLabelText': instance.addItemNamLabelText,
      'addModNameLabelText': instance.addModNameLabelText,
      'addModTootipText': instance.addModTootipText,
      'addModToTooltipText': instance.addModToTooltipText,
      'favLabelText': instance.favLabelText,
      'accessoriesLabelText': instance.accessoriesLabelText,
      'basewearsLabelText': instance.basewearsLabelText,
      'bodypaintsLabelText': instance.bodypaintsLabelText,
      'emotesLabelText': instance.emotesLabelText,
      'innerLabelText': instance.innerLabelText,
      'miscLabelText': instance.miscLabelText,
      'motionsLabelText': instance.motionsLabelText,
      'outerLabelText': instance.outerLabelText,
      'setwearsLabelText': instance.setwearsLabelText,
      'unapplyThisModTooltipText': instance.unapplyThisModTooltipText,
      'applyThisModTooltipText': instance.applyThisModTooltipText,
      'modNameLabelText': instance.modNameLabelText,
      'modsSetSaveTooltipText': instance.modsSetSaveTooltipText,
      'modsSetClickTooltipText': instance.modsSetClickTooltipText,
      'applyModUnderTooltipText': instance.applyModUnderTooltipText,
      'toTheGameTooltipText': instance.toTheGameTooltipText,
      'unapplyModUnderTooltipText': instance.unapplyModUnderTooltipText,
      'fromTheGameTooltipText': instance.fromTheGameTooltipText,
      'newSetNameLabelText': instance.newSetNameLabelText,
      'addNewSetTootipText': instance.addNewSetTootipText,
      'addSetBtnText': instance.addSetBtnText,
      'holdToDeleteBtnTooltipText': instance.holdToDeleteBtnTooltipText,
      'holdToRemoveBtnTooltipText': instance.holdToRemoveBtnTooltipText,
      'holdToReapplyBtnTooltipText': instance.holdToReapplyBtnTooltipText,
      'holdToRemoveAllBtnTooltipText': instance.holdToRemoveAllBtnTooltipText,
      'itemsLabelText': instance.itemsLabelText,
      'itemLabelText': instance.itemLabelText,
      'fileAppliedColonLabelText': instance.fileAppliedColonLabelText,
      'fileAppliedLabelText': instance.fileAppliedLabelText,
      'closeBtnText': instance.closeBtnText,
      'openBtnTooltipText': instance.openBtnTooltipText,
      'addBtnText': instance.addBtnText,
      'addBtnTooltipText': instance.addBtnTooltipText,
      'removeBtnTooltipText': instance.removeBtnTooltipText,
      'deleteBtnTooltipText': instance.deleteBtnTooltipText,
      'refreshingLabelText': instance.refreshingLabelText,
      'modscolonLableText': instance.modscolonLableText,
      'appliedcolonLabelText': instance.appliedcolonLabelText,
      'toFavTooltipText': instance.toFavTooltipText,
      'fromFavTooltipText': instance.fromFavTooltipText,
      'doneBtnText': instance.doneBtnText,
      'filesLabelText': instance.filesLabelText,
      'fileLabelText': instance.fileLabelText,
      'curFilesInSetAppliedTooltipText':
          instance.curFilesInSetAppliedTooltipText,
      'deleteCatPopupText': instance.deleteCatPopupText,
      'deleteCatPopupMsgText': instance.deleteCatPopupMsgText,
      'cannotDeleteCatPopupText': instance.cannotDeleteCatPopupText,
      'cannotDeleteCatPopupUnapplyText':
          instance.cannotDeleteCatPopupUnapplyText,
      'deleteItemPopupText': instance.deleteItemPopupText,
      'deleteItemPopupMsgText': instance.deleteItemPopupMsgText,
      'deleteModPopupText': instance.deleteModPopupText,
      'deleteModPopupMsgText': instance.deleteModPopupMsgText,
      'unappyFilesFirstMsgText': instance.unappyFilesFirstMsgText,
      'removeFromFavFirstMsgText': instance.removeFromFavFirstMsgText,
      'noSearchResultFoundText': instance.noSearchResultFoundText,
      'fromText': instance.fromText,
      'loadingUIText': instance.loadingUIText,
      'checksumSelectPopupText': instance.checksumSelectPopupText,
      'newUpdateAvailText': instance.newUpdateAvailText,
      'newAppVerText': instance.newAppVerText,
      'curAppVerText': instance.curAppVerText,
      'patchNoteLabelText': instance.patchNoteLabelText,
      'updateBtnText': instance.updateBtnText,
      'dismissBtnText': instance.dismissBtnText,
      'waitingUserActionText': instance.waitingUserActionText,
      'pso2binReselectPopupText': instance.pso2binReselectPopupText,
      'modmanReselectPopupText': instance.modmanReselectPopupText,
      'curPathText': instance.curPathText,
      'chooseNewPathText': instance.chooseNewPathText,
      'newCatNameEmptyErrorText': instance.newCatNameEmptyErrorText,
      'newCatNameDupErrorText': instance.newCatNameDupErrorText,
      'newItemNameEmpty': instance.newItemNameEmpty,
      'newItemNameDuplicate': instance.newItemNameDuplicate,
      'multiItemsLeftOver': instance.multiItemsLeftOver,
      'originalFileOf': instance.originalFileOf,
      'isNotFound': instance.isNotFound,
      'replaced': instance.replaced,
      'backupFileOf': instance.backupFileOf,
      'setRemovalErrorText': instance.setRemovalErrorText,
      'pso2binNotFoundPopupText': instance.pso2binNotFoundPopupText,
      'modmanFolderNotFoundLabelText': instance.modmanFolderNotFoundLabelText,
      'modmanFolderNotFoundText': instance.modmanFolderNotFoundText,
      'addModsBtnLabel': instance.addModsBtnLabel,
      'addModsTooltip': instance.addModsTooltip,
      'checksumDownloadingBtnLabel': instance.checksumDownloadingBtnLabel,
      'itemRefUpdateAvailableText': instance.itemRefUpdateAvailableText,
      'downloadingText': instance.downloadingText,
      'filesOfText': instance.filesOfText,
      'downloadUpdateBtnLabel': instance.downloadUpdateBtnLabel,
      'sortCategoryTooltipText': instance.sortCategoryTooltipText,
      'sortCateByNameText': instance.sortCateByNameText,
      'sortCateByNumItemsText': instance.sortCateByNumItemsText,
      'preparingLabelText': instance.preparingLabelText,
      'dragNdropBoxLabelText': instance.dragNdropBoxLabelText,
      'removeBtnLabel': instance.removeBtnLabel,
      'clearAllBtnLabel': instance.clearAllBtnLabel,
      'progressBtnLabel': instance.progressBtnLabel,
      'waitingForDataLabelText': instance.waitingForDataLabelText,
      'errorLoadingRestartApp': instance.errorLoadingRestartApp,
      'editTooltipText': instance.editTooltipText,
      'renameSpaceLabelText': instance.renameSpaceLabelText,
      'spaceBeforeAddingLabelText': instance.spaceBeforeAddingLabelText,
      'errorModsInToBeAddedListLabelText':
          instance.errorModsInToBeAddedListLabelText,
      'returnBtnLabel': instance.returnBtnLabel,
      'addAllBtnLabelText': instance.addAllBtnLabelText,
      'errorFilesNotSupportedText': instance.errorFilesNotSupportedText,
      'checksumHoldBtnTooltip': instance.checksumHoldBtnTooltip,
      'modsLabelText': instance.modsLabelText,
      'modLabelText': instance.modLabelText,
      'modAddedSuccessfullyText': instance.modAddedSuccessfullyText,
      'preparingItemsText': instance.preparingItemsText,
      'mayTakeSomeTimeText': instance.mayTakeSomeTimeText,
      'removeItemFromAdding': instance.removeItemFromAdding,
      'removeModFromAdding': instance.removeModFromAdding,
      'addItemBackToAdding': instance.addItemBackToAdding,
      'addModBackToAdding': instance.addModBackToAdding,
      'newUserNoticeText': instance.newUserNoticeText,
      'skipVersionUpdateBtnLabel': instance.skipVersionUpdateBtnLabel,
      'clickContinueIfStuckBtnLabel': instance.clickContinueIfStuckBtnLabel,
      'singleFileAppliedLabelText': instance.singleFileAppliedLabelText,
      'titleNewUpdateToolTip': instance.titleNewUpdateToolTip,
      'nameCannotBeEmptyErrorText': instance.nameCannotBeEmptyErrorText,
      'nameAlreadyExistsErrorText': instance.nameAlreadyExistsErrorText,
      'checksumOutdatedErrorText': instance.checksumOutdatedErrorText,
      'downloadChecksumFirstTooltipText':
          instance.downloadChecksumFirstTooltipText,
    };
